import {FormEvent,useEffect,useRef,useState} from 'react';
import type {Entity,Role,User} from '../../../types';
import type {UserDraft} from '../types/user.types';
import {ClientScopeSelector} from './ClientScopeSelector';
import {RoleSelector} from './RoleSelector';

const initial=(user?:User|null):UserDraft=>({full_name:user?.full_name||'',email:user?.email||'',mobile:user?.mobile||'',role_name:user?.role||'',entity_ids:user?.entity_ids||[],is_active:user?.is_active??true,temporary_password:''});
export function UserForm({open,user,roles,clients,busy,error,onClose,onSubmit}:{open:boolean;user:User|null;roles:Role[];clients:Entity[];busy:boolean;error:string;onClose:()=>void;onSubmit:(draft:UserDraft)=>void}){
  const ref=useRef<HTMLDialogElement>(null),[draft,setDraft]=useState<UserDraft>(()=>initial(user));useEffect(()=>setDraft(initial(user)),[user,open]);useEffect(()=>{if(open&&!ref.current?.open)ref.current?.showModal();if(!open&&ref.current?.open)ref.current.close()},[open]);const scoped=draft.role_name!=='Admin / Partner',required=draft.role_name==='Client Management'||draft.role_name==='Client / Management';
  function submit(event:FormEvent){event.preventDefault();if(required&&!draft.entity_ids.length)return;onSubmit(draft)}
  return <dialog className="user-dialog" ref={ref} onCancel={event=>{event.preventDefault();onClose()}}><div className="dialog-head"><div><p className="eyebrow">ADMINISTRATION</p><h2>{user?'Edit user':'Create user'}</h2></div><button aria-label="Close" onClick={onClose}>×</button></div><form className="user-form" onSubmit={submit}><div className="form-grid"><label>Full name *<input required maxLength={160} value={draft.full_name} onChange={event=>setDraft({...draft,full_name:event.target.value})}/></label><label>Email *<input required disabled={Boolean(user)} type="email" value={draft.email} onChange={event=>setDraft({...draft,email:event.target.value})}/></label><label>Mobile<input maxLength={30} inputMode="tel" value={draft.mobile} onChange={event=>setDraft({...draft,mobile:event.target.value})}/></label><RoleSelector roles={roles} value={draft.role_name} onChange={role_name=>setDraft({...draft,role_name,entity_ids:role_name==='Admin / Partner'?[]:draft.entity_ids})}/>{!user&&<label>Temporary password *<input required type="password" minLength={12} autoComplete="new-password" value={draft.temporary_password} onChange={event=>setDraft({...draft,temporary_password:event.target.value})}/></label>} {!user&&<label>Status<select value={draft.is_active?'active':'inactive'} onChange={event=>setDraft({...draft,is_active:event.target.value==='active'})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label>}</div>{scoped&&<ClientScopeSelector clients={clients} value={draft.entity_ids} required={required} onChange={entity_ids=>setDraft({...draft,entity_ids})}/>} {required&&!draft.entity_ids.length&&<div className="field-hint error-text">Select at least one client for Client Management.</div>}{user&&user.role!==draft.role_name&&<div className="warning">Changing this role will change the user’s effective permissions.</div>}{error&&<div className="alert">{error}</div>}<div className="dialog-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy||required&&!draft.entity_ids.length}>{busy?'Saving…':user?'Save changes':'Create user'}</button></div></form></dialog>;
}
