import {useEffect,useState} from "react";
import {api} from "../services/api";
import type {Observation} from "../types";

const statuses=['Pending','Management Responded','Resolved','Repeated','Closed'];
type History={id:string;action:string;old_value:Record<string,unknown>|null;new_value:Record<string,unknown>|null;created_at:string};
export function ObservationRegisterPage(){
  const [rows,setRows]=useState<Observation[]>([]),[status,setStatus]=useState(''),[risk,setRisk]=useState(''),[query,setQuery]=useState(''),[history,setHistory]=useState<Record<string,History[]>>({}),[expanded,setExpanded]=useState(''),[msg,setMsg]=useState('');const reload=()=>api.observations().then(setRows);useEffect(()=>{reload()},[]);const filtered=rows.filter(item=>(!status||item.status===status)&&(!risk||item.risk===risk)&&(!query||`${item.observation} ${item.remark} ${item.responsible_person}`.toLowerCase().includes(query.toLowerCase())));
  async function transition(row:Observation,next:string){try{await api.updateObservation(row.id,{status:next,expected_version:row.version});setMsg(`Observation moved to ${next}`);reload()}catch(x){setMsg(`Error: ${(x as Error).message}`);reload()}}async function toggleHistory(id:string){if(expanded===id){setExpanded('');return}setExpanded(id);if(!history[id])try{const entries=await api.observationHistory(id);setHistory(current=>({...current,[id]:entries}))}catch(x){setMsg(`Error: ${(x as Error).message}`)}}
  return <section className="panel"><div className="panel-head"><h2>Observation register</h2><button onClick={()=>api.exportObservations()}>Export CSV</button></div><div className="form-grid"><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Observation, remark, or responsible person"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(item=><option key={item}>{item}</option>)}</select></label><label>Risk<select value={risk} onChange={e=>setRisk(e.target.value)}><option value="">All risks</option>{['Low','Medium','High','Critical'].map(item=><option key={item}>{item}</option>)}</select></label></div>{msg&&<div className={msg.startsWith('Error:')?'alert':'notice'}>{msg}</div>}{filtered.length===0&&<div className="empty"><strong>No observations match the filters</strong></div>}{filtered.map(row=><article className="reply-card" key={row.id}><div><span className={`badge ${row.risk.toLowerCase()}`}>{row.risk}</span><strong>{row.observation}</strong><small>{row.period} · {row.responsible_person||'Unassigned'} · {row.locked_at?'Locked':row.status}</small></div><div>{row.remark||'No auditor remark'}</div>{!row.locked_at&&<select value={row.status} onChange={e=>transition(row,e.target.value)}>{statuses.map(item=><option key={item}>{item}</option>)}</select>}<button onClick={()=>toggleHistory(row.id)}>{expanded===row.id?'Hide history':'View history'}</button>{expanded===row.id&&<div>{(history[row.id]||[]).map(entry=><div className="metric-row" key={entry.id}><span>{entry.action}<small>{new Date(entry.created_at).toLocaleString()}</small></span><code>{JSON.stringify(entry.new_value||{})}</code></div>)}</div>}</article>)}</section>;
}
