import {FormEvent,useEffect,useState} from "react";
import {api} from "../services/api";
import type {Area,Entity,Plan,User} from "../types";

const month=()=>new Date().toISOString().slice(0,7),day=()=>new Date().toISOString().slice(0,10);
export function PlanningPage(){
  const [entities,setEntities]=useState<Entity[]>([]),[areas,setAreas]=useState<Area[]>([]),[assignees,setAssignees]=useState<User[]>([]),[rows,setRows]=useState<Plan[]>([]),[entity,setEntity]=useState(''),[area,setArea]=useState(''),[assigned,setAssigned]=useState<string[]>([]),[period,setPeriod]=useState(month()),[due,setDue]=useState(day()),[msg,setMsg]=useState('');
  const reload=()=>api.plans().then(setRows);useEffect(()=>{Promise.all([api.entities(),api.areas(),api.assignees(),api.plans()]).then(([entityRows,areaRows,userRows,plans])=>{setEntities(entityRows);setAreas(areaRows);setAssignees(userRows);setRows(plans);if(entityRows[0])setEntity(entityRows[0].id);if(areaRows[0])setArea(areaRows[0].id)}).catch(x=>setMsg(`Error: ${x.message}`))},[]);
  const payload=()=>({entity_id:entity,period,due_date:due,assigned_user_ids:assigned});
  async function submit(event:FormEvent){event.preventDefault();try{await api.createPlan({...payload(),audit_area_id:area});setMsg('Audit plan created and assigned');reload()}catch(x){setMsg(`Error: ${(x as Error).message}`)}}async function fullMonth(){try{const plans=await api.createFullMonthPlan(payload());setMsg(`${plans.length} audit areas planned and assigned`);reload()}catch(x){setMsg(`Error: ${(x as Error).message}`)}}async function carry(){try{const result=await api.carryForward({entity_id:entity,target_period:period});setMsg(`${result.count} observations carried from ${result.source_period}`)}catch(x){setMsg(`Error: ${(x as Error).message}`)}}async function changeStatus(plan:Plan,status:string){try{await api.updatePlan(plan.id,{status,expected_version:plan.version});setMsg('Plan status updated');reload()}catch(x){setMsg(`Error: ${(x as Error).message}`);reload()}}
  return <><section className="panel"><h2>Create monthly audit plan</h2><form className="form-grid" onSubmit={submit}><label>Entity<select required value={entity} onChange={e=>setEntity(e.target.value)}>{entities.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Audit area<select required value={area} onChange={e=>setArea(e.target.value)}>{areas.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Period<input required type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><label>Due date<input required type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><fieldset><legend>Assign audit team</legend>{assignees.length===0?<span className="muted">No active audit staff or managers</span>:assignees.map(user=><label className="checkbox" key={user.id}><input type="checkbox" checked={assigned.includes(user.id)} onChange={()=>setAssigned(current=>current.includes(user.id)?current.filter(id=>id!==user.id):[...current,user.id])}/>{user.full_name} ({user.role})</label>)}</fieldset><button className="primary">Create plan</button><button type="button" onClick={fullMonth}>Plan all areas</button><button type="button" onClick={carry}>Carry forward pending</button></form>{msg&&<div className={msg.startsWith('Error:')?'alert':'notice'}>{msg}</div>}</section><section className="panel"><h2>Audit calendar</h2>{rows.length===0&&<div className="empty"><strong>No audit plans yet</strong></div>}{rows.map(plan=><article className="report-row" key={plan.id}><div><strong>{plan.period}</strong><small>Due {plan.due_date}</small></div><select aria-label={`Status for ${plan.period}`} value={plan.status} onChange={e=>changeStatus(plan,e.target.value)}>{['Pending','In Progress','Completed','Overdue'].map(status=><option key={status}>{status}</option>)}</select></article>)}</section></>;
}
