import {FormEvent,useEffect,useState} from "react";
import {api} from "../services/api";
import type {Entity,Report} from "../types";

const month=()=>new Date().toISOString().slice(0,7);
export function ReportsPage({permissions}:{permissions:string[]}){
  const [entities,setEntities]=useState<Entity[]>([]),[rows,setRows]=useState<Report[]>([]),[entity,setEntity]=useState(''),[period,setPeriod]=useState(month()),[type,setType]=useState('Monthly Internal Audit Report'),[msg,setMsg]=useState('');const canGenerate=permissions.includes('GENERATE_REPORT'),canApprove=permissions.includes('APPROVE_REPORT');
  const reload=()=>api.reports().then(setRows);useEffect(()=>{reload();api.entities().then(items=>{setEntities(items);if(items[0])setEntity(items[0].id)})},[]);
  async function generate(event:FormEvent){event.preventDefault();try{await api.generateReport({entity_id:entity,period,report_type:type});setMsg('Report generated from authoritative database records');reload()}catch(x){setMsg(`Error: ${(x as Error).message}`)}}async function approve(id:string){try{await api.approveReport(id);setMsg('Report approved and all applicable observations locked');reload()}catch(x){setMsg(`Error: ${(x as Error).message}`)}}
  return <>{canGenerate&&<section className="panel"><h2>Generate authoritative report</h2><form className="form-grid" onSubmit={generate}><label>Entity<select required value={entity} onChange={e=>setEntity(e.target.value)}>{entities.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Period<input required type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><label>Report type<select value={type} onChange={e=>setType(e.target.value)}>{['Monthly Internal Audit Report','Mandatory Completion Report','Exception Report','Pending Action Taken Report','GST Compliance Report','TDS Compliance Report','Management Discussion Report'].map(item=><option key={item}>{item}</option>)}</select></label><button className="primary">Generate</button></form></section>}<section className="panel"><h2>Reports & approval</h2>{msg&&<div className={msg.startsWith('Error:')?'alert':'notice'}>{msg}</div>}{rows.length===0&&<div className="empty"><strong>No reports available</strong></div>}{rows.map(report=><article className="report-row" key={report.id}><div><strong>{report.report_type}</strong><small>{report.period} · {report.report_number||'Draft'}</small></div><div className="export-buttons">{['csv','xlsx','docx','pdf'].map(format=><button key={format} onClick={()=>api.downloadReport(report.id,format)}>{format.toUpperCase()}</button>)}</div>{report.status==='Locked'?<span className="badge">Locked</span>:canApprove?<button onClick={()=>approve(report.id)}>Approve & lock</button>:<span className="badge">{report.status}</span>}</article>)}</section></>;
}
