import {FormEvent,useEffect,useState} from "react";
import {ConfirmDialog} from "../components/ConfirmDialog";
import {api} from "../services/api";
import type {Area,Checklist,DocumentRecord,Entity,Observation} from "../types";

const month=()=>new Date().toISOString().slice(0,7);
function Notice({value}:{value:string}){return value?<div className={value.startsWith('Error:')?'alert':'notice'}>{value}</div>:null}
function useSetup(){const [entities,setEntities]=useState<Entity[]>([]),[areas,setAreas]=useState<Area[]>([]);const reload=()=>Promise.all([api.entities(),api.areas()]).then(([e,a])=>{setEntities(e);setAreas(a)});useEffect(()=>{reload()},[]);return {entities,areas,reload}}

export function RepliesPage(){
  const [rows,setRows]=useState<Observation[]>([]),[comments,setComments]=useState<Record<string,string>>({}),[actions,setActions]=useState<Record<string,string>>({}),[msg,setMsg]=useState('');
  const reload=()=>api.observations().then(x=>setRows(x.filter(o=>['Pending','Repeated','Management Responded'].includes(o.status))));useEffect(()=>{reload()},[]);
  async function reply(id:string){try{await api.reply(id,{comment:comments[id]||'',action_taken:actions[id]||''});setMsg('Management reply recorded in the immutable history');setComments(current=>({...current,[id]:''}));setActions(current=>({...current,[id]:''}));reload()}catch(x){setMsg(`Error: ${(x as Error).message}`)}}
  return <section className="panel"><h2>Management response queue</h2><Notice value={msg}/>{rows.length===0&&<div className="empty"><strong>No observations awaiting response</strong></div>}{rows.map(row=><article className="reply-card" key={row.id}><div><span className="badge">{row.risk}</span><strong>{row.observation}</strong><small>{row.period} · {row.status}</small></div><label>Management comment<textarea value={comments[row.id]||''} onChange={e=>setComments({...comments,[row.id]:e.target.value})}/></label><label>Action taken<textarea value={actions[row.id]||''} onChange={e=>setActions({...actions,[row.id]:e.target.value})}/></label><button onClick={()=>reply(row.id)} disabled={!comments[row.id]?.trim()}>Submit response</button></article>)}</section>;
}

export function DocumentsPage(){
  const {entities,areas}=useSetup(),[rows,setRows]=useState<DocumentRecord[]>([]),[observations,setObservations]=useState<Observation[]>([]),[checks,setChecks]=useState<Checklist[]>([]),[entity,setEntity]=useState(''),[area,setArea]=useState(''),[period,setPeriod]=useState(month()),[observation,setObservation]=useState(''),[checklist,setChecklist]=useState(''),[documentType,setDocumentType]=useState('Other Working Paper'),[remarks,setRemarks]=useState(''),[file,setFile]=useState<File|null>(null),[pendingArchive,setPendingArchive]=useState<DocumentRecord|null>(null),[msg,setMsg]=useState('');
  const reload=()=>api.documents().then(setRows);useEffect(()=>{reload()},[]);useEffect(()=>{if(!entity&&entities[0])setEntity(entities[0].id);if(!area&&areas[0])setArea(areas[0].id)},[entities,areas]);useEffect(()=>{if(entity)api.observations({entity_id:entity,period}).then(setObservations)},[entity,period]);useEffect(()=>{if(area)api.checklists(area).then(setChecks)},[area]);
  async function submit(event:FormEvent){event.preventDefault();if(!file)return;const data=new FormData();data.set('entity_id',entity);data.set('audit_area_id',area);data.set('period',period);data.set('document_type',documentType);data.set('remarks',remarks);if(observation)data.set('observation_id',observation);if(checklist)data.set('checklist_item_id',checklist);data.set('file',file);try{await api.uploadDocument(data);setMsg('Document uploaded to protected local file storage');setFile(null);setRemarks('');reload()}catch(x){setMsg(`Error: ${(x as Error).message}`)}}
  async function archive(){if(!pendingArchive)return;try{await api.archiveDocument(pendingArchive.id);setMsg(`${pendingArchive.file_name} archived; the physical evidence file was retained`);setPendingArchive(null);reload()}catch(x){setMsg(`Error: ${(x as Error).message}`)}}
  return <><section className="panel"><h2>Upload audit evidence</h2><form className="form-grid" onSubmit={submit}><label>Entity<select required value={entity} onChange={e=>setEntity(e.target.value)}>{entities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Audit area<select required value={area} onChange={e=>{setArea(e.target.value);setChecklist('')}}>{areas.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Period<input required type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><label>Document type<select value={documentType} onChange={e=>setDocumentType(e.target.value)}>{['Other Working Paper','Supporting Evidence','Management Response','Reconciliation','Compliance Return'].map(x=><option key={x}>{x}</option>)}</select></label><label>Observation (optional)<select value={observation} onChange={e=>setObservation(e.target.value)}><option value="">Not linked</option>{observations.map(item=><option key={item.id} value={item.id}>{item.observation.slice(0,70)}</option>)}</select></label><label>Checklist item (optional)<select value={checklist} onChange={e=>setChecklist(e.target.value)}><option value="">Not linked</option>{checks.map(item=><option key={item.id} value={item.id}>{item.question.slice(0,70)}</option>)}</select></label><label>Remarks<input maxLength={4000} value={remarks} onChange={e=>setRemarks(e.target.value)}/></label><label>File<input required type="file" accept=".pdf,.jpg,.jpeg,.png,.xlsx,.docx,.csv,.txt" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={!file}>Upload securely</button></form><Notice value={msg}/></section><section className="panel"><h2>Document register</h2>{rows.length===0&&<div className="empty"><strong>No documents uploaded</strong></div>}{rows.map(d=><article className="report-row" key={d.id}><div><strong>{d.file_name}</strong><small>{d.period} · {d.document_type} · {(d.file_size/1024).toFixed(1)} KB</small></div><button onClick={()=>api.downloadDocument(d.id,d.file_name)}>Download</button><button className="danger" onClick={()=>setPendingArchive(d)}>Archive</button></article>)}</section><ConfirmDialog open={Boolean(pendingArchive)} title="Archive document?" message={`Archive ${pendingArchive?.file_name||'this document'} from the active register? The stored evidence file is retained for audit recovery.`} confirmLabel="Archive document" onCancel={()=>setPendingArchive(null)} onConfirm={archive}/></>;
}

export function DocumentRegisterPage(){
  const [rows,setRows]=useState<DocumentRecord[]>([]),[msg,setMsg]=useState('');useEffect(()=>{api.documents().then(setRows).catch(x=>setMsg(`Error: ${x.message}`))},[]);
  return <section className="panel"><h2>Document register</h2><Notice value={msg}/>{rows.length===0&&<div className="empty"><strong>No documents available</strong></div>}{rows.map(document=><article className="report-row" key={document.id}><div><strong>{document.file_name}</strong><small>{document.period} · {document.document_type} · {(document.file_size/1024).toFixed(1)} KB</small></div><button onClick={()=>api.downloadDocument(document.id,document.file_name)}>Download</button></article>)}</section>;
}

export function MastersPage(){
  const {entities,areas,reload}=useSetup(),[name,setName]=useState(''),[code,setCode]=useState(''),[areaName,setAreaName]=useState(''),[selectedArea,setSelectedArea]=useState(''),[question,setQuestion]=useState(''),[firm,setFirm]=useState(''),[client,setClient]=useState(''),[prefix,setPrefix]=useState('IA/MWB'),[financialYear,setFinancialYear]=useState(''),[msg,setMsg]=useState(''),[pending,setPending]=useState<{type:'entity'|'area';id:string;name:string}|null>(null);
  useEffect(()=>{if(!selectedArea&&areas[0])setSelectedArea(areas[0].id)},[areas]);useEffect(()=>{api.settings().then(settings=>{const value=(key:string,fallback='')=>{const item=settings[key];if(typeof item==='string')return item;return String(item?.value||fallback)};setFirm(value('firm'));setClient(value('client'));setPrefix(value('report_prefix','IA/MWB'));setFinancialYear(value('financial_year'))})},[]);
  async function addEntity(e:FormEvent){e.preventDefault();try{await api.createEntity({name,code});setMsg('Entity created');setName('');setCode('');reload()}catch(x){setMsg(`Error: ${(x as Error).message}`)}}async function addArea(e:FormEvent){e.preventDefault();try{await api.createArea({name:areaName,sort_order:areas.length+1});setMsg('Audit area created');setAreaName('');reload()}catch(x){setMsg(`Error: ${(x as Error).message}`)}}async function addCheck(e:FormEvent){e.preventDefault();try{await api.createChecklist({audit_area_id:selectedArea,question,is_mandatory:true,sort_order:999});setMsg('Mandatory checklist item created');setQuestion('')}catch(x){setMsg(`Error: ${(x as Error).message}`)}}async function saveSettings(e:FormEvent){e.preventDefault();try{await Promise.all([api.updateSetting('firm',{value:firm}),api.updateSetting('client',{value:client}),api.updateSetting('report_prefix',{value:prefix}),api.updateSetting('financial_year',{value:financialYear})]);setMsg('Report settings saved')}catch(x){setMsg(`Error: ${(x as Error).message}`)}}async function deactivate(){if(!pending)return;try{if(pending.type==='entity')await api.updateEntity(pending.id,{is_active:false});else await api.updateArea(pending.id,{is_active:false});setMsg(`${pending.name} archived`);setPending(null);reload()}catch(x){setMsg(`Error: ${(x as Error).message}`)}}
  return <><section className="panel"><h2>Firm and report settings</h2><form className="form-grid" onSubmit={saveSettings}><label>Firm name<input required value={firm} onChange={e=>setFirm(e.target.value)}/></label><label>Client / group name<input required value={client} onChange={e=>setClient(e.target.value)}/></label><label>Report prefix<input required value={prefix} onChange={e=>setPrefix(e.target.value)}/></label><label>Financial year<input required placeholder="2026-27" value={financialYear} onChange={e=>setFinancialYear(e.target.value)}/></label><button className="primary">Save settings</button></form><Notice value={msg}/></section><div className="split"><section className="panel"><h2>Add entity</h2><form className="form-grid" onSubmit={addEntity}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Code<input value={code} onChange={e=>setCode(e.target.value)}/></label><button className="primary">Add entity</button></form>{entities.map(item=><article className="report-row" key={item.id}><div><strong>{item.name}</strong><small>{item.code||'No code'}</small></div><button className="danger" onClick={()=>setPending({type:'entity',id:item.id,name:item.name})}>Archive</button></article>)}</section><section className="panel"><h2>Add audit area</h2><form className="form-grid" onSubmit={addArea}><label>Name<input value={areaName} onChange={e=>setAreaName(e.target.value)} required/></label><button className="primary">Add area</button></form>{areas.map(item=><article className="report-row" key={item.id}><div><strong>{item.name}</strong><small>Order {item.sort_order}</small></div><button className="danger" onClick={()=>setPending({type:'area',id:item.id,name:item.name})}>Archive</button></article>)}</section></div><section className="panel"><h2>Add checklist item</h2><form className="form-grid" onSubmit={addCheck}><label>Audit area<select value={selectedArea} onChange={e=>setSelectedArea(e.target.value)}>{areas.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Mandatory question<input value={question} onChange={e=>setQuestion(e.target.value)} required/></label><button className="primary">Add checklist item</button></form></section><ConfirmDialog open={Boolean(pending)} title={`Archive ${pending?.type||'record'}?`} message={`${pending?.name||'This record'} will be removed from active selection lists. Existing audit history remains intact.`} confirmLabel="Archive" onCancel={()=>setPending(null)} onConfirm={deactivate}/></>;
}
