import {FormEvent,useEffect,useState} from "react";
import {Navigate,NavLink,Route,Routes,useLocation,useNavigate} from "react-router-dom";
import {api,ApiError,authStore} from "./services/api";
import type {Area,Entity,Observation,Plan,Report,Summary,User} from "./types";
import {AuditEntryPage} from "./pages/EnhancedOperations";
import {ChangePasswordPage} from "./pages/Account";
import {AdminPage} from "./pages/Administration";
import {DocumentRegisterPage,DocumentsPage,MastersPage,RepliesPage} from "./pages/SupportingOperations";
import {ReportsPage} from "./pages/ReportOperations";
import {PlanningPage} from "./pages/PlanningOperations";
import {ObservationRegisterPage} from "./pages/ObservationOperations";

const nav=[['/','Overview','VIEW_DASHBOARD'],['/planning','Audit calendar','VIEW_AUDIT_PLAN'],['/entry','Audit entry','CREATE_OBSERVATION'],['/observations','Observations','VIEW_AUDIT_ENTRY'],['/replies','Client replies','VIEW_CLIENT_REPLY'],['/reports','Reports & approval','VIEW_REPORT'],['/documents','Documents','VIEW_DOCUMENT'],['/masters','Masters','MANAGE_ENTITIES'],['/admin','Users','MANAGE_USERS']] as const;

function Login({onLogin}:{onLogin:(u:User)=>void}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const tokens=await api.login(email,password);authStore.set(tokens.access_token,tokens.refresh_token);onLogin(await api.me())}catch(err){setError(err instanceof ApiError?err.message:'Unable to reach the service')}finally{setBusy(false)}}return <main className="login"><section className="login-card"><div className="brand-mark">HA</div><p className="eyebrow">Hombal & Associates</p><h1>Internal Audit Manager</h1><p className="muted">Secure audit planning, execution, management response, and report approval.</p><form onSubmit={submit}><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="alert">{error}</div>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form></section></main>}

function Shell({user,onLogout}:{user:User;onLogout:()=>void}){const location=useLocation();const visibleNav=nav.filter(([, ,permission])=>user.permissions.includes(permission));const allowed=(permission:string,element:React.ReactNode)=>user.permissions.includes(permission)?element:<Navigate to="/"/>;return <div className="shell"><aside><div className="brand"><div className="brand-mark small">HA</div><div><strong>MWB Audit</strong><span>Internal Audit Manager</span></div></div><nav>{visibleNav.map(([to,label])=><NavLink key={to} to={to} end={to==='/' }>{label}</NavLink>)}</nav><div className="profile"><div className="avatar">{user.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><strong>{user.full_name}</strong><span>{user.role}</span></div><button aria-label="Sign out" onClick={onLogout}>↗</button></div></aside><main className="content"><header><div><p className="eyebrow">MWB GROUP · INTERNAL AUDIT</p><h1>{nav.find(([to])=>to===location.pathname)?.[1]||'Internal Audit Manager'}</h1></div><div className="period">FY 2026–27</div></header><Routes><Route path="/" element={<Dashboard/>}/><Route path="/planning" element={allowed('VIEW_AUDIT_PLAN',user.permissions.includes('CREATE_AUDIT_PLAN')?<PlanningPage/>:<Planning/>)}/><Route path="/entry" element={allowed('CREATE_OBSERVATION',<AuditEntryPage/>)}/><Route path="/observations" element={allowed('VIEW_AUDIT_ENTRY',user.permissions.includes('EDIT_OBSERVATION')?<ObservationRegisterPage/>:<Observations/>)}/><Route path="/replies" element={allowed('VIEW_CLIENT_REPLY',<RepliesPage/>)}/><Route path="/reports" element={allowed('VIEW_REPORT',<ReportsPage permissions={user.permissions}/>)}/><Route path="/documents" element={allowed('VIEW_DOCUMENT',user.permissions.includes('UPLOAD_DOCUMENT')?<DocumentsPage/>:<DocumentRegisterPage/>)}/><Route path="/masters" element={allowed('MANAGE_ENTITIES',<MastersPage/>)}/><Route path="/admin" element={allowed('MANAGE_USERS',<AdminPage/>)}/><Route path="*" element={<Navigate to="/"/>}/></Routes></main></div>}

function Load<T>({load,children}:{load:()=>Promise<T>;children:(data:T)=>React.ReactNode}){const [data,setData]=useState<T>();const [error,setError]=useState('');useEffect(()=>{load().then(setData).catch(e=>setError(e.message))},[]);if(error)return <div className="alert">{error}</div>;if(!data)return <div className="loading">Loading authoritative data…</div>;return <>{children(data)}</>}
function Dashboard(){return <><Load load={api.summary}>{(s:Summary)=><><section className="stats"><Stat label="Total observations" value={s.total_observations}/><Stat label="Pending / repeated" value={s.pending_repeated} tone="amber"/><Stat label="High / critical" value={s.high_critical} tone="red"/><Stat label="Locked reports" value={s.locked_reports} tone="green"/></section><section className="split"><div className="panel"><h2>Attention required</h2><div className="attention"><strong>{s.overdue_observations}</strong><span>overdue observations</span></div><div className="attention"><strong>{s.due_plans}</strong><span>upcoming audit plans</span></div></div><div className="panel hero-panel"><p className="eyebrow">CONTROL STATUS</p><h2>Approval rules are enforced on the server</h2><p>Reports can only be locked after every mandatory checklist item is complete for one entity and period.</p><NavLink className="button" to="/reports">Review reports</NavLink></div></section></>}</Load><Load load={api.analytics}>{a=><section className="analytics-grid"><MetricList title="Risk distribution" rows={a.risk_distribution}/><MetricList title="Observation status" rows={a.status_distribution}/><MetricList title="Entity-wise status" rows={a.entity_status}/><section className="panel"><h2>Upcoming audits</h2>{a.upcoming_audits.map((x,i)=><div className="metric-row" key={i}><span>{x.entity}<small>{x.period}</small></span><strong>{x.due_date}</strong></div>)}</section></section>}</Load></>}
function MetricList({title,rows}:{title:string;rows:{label:string;count:number}[]}){const max=Math.max(1,...rows.map(x=>x.count));return <section className="panel"><h2>{title}</h2>{rows.map(x=><div className="metric-row" key={x.label}><span>{x.label}</span><div className="mini-bar"><i style={{width:`${x.count/max*100}%`}}/></div><strong>{x.count}</strong></div>)}</section>}
function Stat({label,value,tone='blue'}:{label:string;value:number;tone?:string}){return <article className={`stat ${tone}`}><span>{label}</span><strong>{value}</strong><small>Live database metric</small></article>}
function Planning(){return <Load load={()=>api.plans()}>{(rows:Plan[])=><PanelTable title="Audit calendar" headers={['Period','Due date','Status']} rows={rows.map(x=>[x.period,x.due_date,<Badge value={x.status}/>])}/>}</Load>}
function Observations(){return <Load load={api.observations}>{(rows:Observation[])=><PanelTable title="Observation register" headers={['Period','Risk','Observation','Status']} rows={rows.map(x=>[x.period,<Badge value={x.risk}/>,x.observation,<Badge value={x.status}/>])}/>}</Load>}
function Reports(){return <Load load={api.reports}>{(rows:Report[])=><PanelTable title="Generated and approved reports" headers={['Period','Type','Report number','Status']} rows={rows.map(x=>[x.period,x.report_type,x.report_number||'Draft',<Badge value={x.status}/>])}/>}</Load>}
function Masters(){return <div className="split"><Load load={api.entities}>{(rows:Entity[])=><PanelTable title="Entities" headers={['Name','Code']} rows={rows.map(x=>[x.name,x.code||'—'])}/>}</Load><Load load={api.areas}>{(rows:Area[])=><PanelTable title="Audit areas" headers={['Name','Order']} rows={rows.map(x=>[x.name,String(x.sort_order)])}/>}</Load></div>}
function PanelTable({title,headers,rows}:{title:string;headers:string[];rows:React.ReactNode[][]}){return <section className="panel table-panel"><div className="panel-head"><h2>{title}</h2><span>{rows.length} records</span></div>{rows.length?<div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>:<div className="empty"><strong>No records yet</strong><span>New records will appear here after they are created.</span></div>}</section>}
function Badge({value}:{value:string}){return <span className={`badge ${value.toLowerCase().replaceAll(' ','-')}`}>{value}</span>}
function Placeholder({title,text}:{title:string;text:string}){return <section className="panel empty large"><div className="placeholder-icon">✓</div><h2>{title}</h2><p>{text}</p><span>This workspace is connected to the production API foundation.</span></section>}
export function App(){const [user,setUser]=useState<User|null>(null);const [checking,setChecking]=useState(authStore.has());useEffect(()=>{if(authStore.has())api.me().then(setUser).catch(()=>authStore.clear()).finally(()=>setChecking(false))},[]);if(checking)return <div className="splash">MWB Audit</div>;if(!user)return <Login onLogin={setUser}/>;if(user.must_change_password)return <ChangePasswordPage onComplete={()=>setUser(null)}/>;return <Shell user={user} onLogout={()=>{api.logout().finally(()=>{authStore.clear();setUser(null)})}}/>}
